import android1 from "../../assets/android/android1.png";
import android2 from "../../assets/android/android2.png";
import android3 from "../../assets/android/android3.png";
import android4 from "../../assets/android/android4.png";
import android6 from "../../assets/android/android6.png";
import android7 from "../../assets/android/android7.png";
import android8 from "../../assets/android/android8.png";
import android9 from "../../assets/android/android9.png";

import ios1 from "../../assets/ios/ios1.png";
import ios2 from "../../assets/ios/ios2.png";
import ios3 from "../../assets/ios/ios3.png";
import ios4 from "../../assets/ios/ios4.png";
import ios5 from "../../assets/ios/ios5.png";
import ios6 from "../../assets/ios/ios6.png";
import ios7 from "../../assets/ios/ios7.png";
import ios8 from "../../assets/ios/ios8.png";
import ios9 from "../../assets/ios/ios9.png";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */
export const products = [
  {
    _id: "3d7e9c33-0080-4bd2-b2bf-56552da31e35",
    qty: 0,
    name: "Galaxy S7",
    description:
      "Smartphone avec un écran Super AMOLED de 5,1 pouces et un appareil photo de 12 MP.",
    brand: "Samsung",
    category: "android",
    gender: "4",
    weight: "64",
    quantity: 1,
    image: android1,
    rating: 4.5,
    price: 200,
    newPrice: 175,
    trending: true,
  },
  {
    _id: "887cdd99-1503-4527-aef4-88c521126a47",
    qty: 0,
    name: "Galaxy S8",
    description:
      "Téléphone avec un écran Infinity de 5,8 pouces, un appareil photo de 12 MP et reconnaissance d'iris.",
    brand: "Samsung",
    category: "android",
    gender: "4",
    weight: "128",
    quantity: 1,
    image: android2,
    rating: 4.8,
    price: 300,
    newPrice: 250,
    trending: true,
  },
  {
    _id: "dc2b2495-eb6c-4889-a6f7-3c8853a01ba2",
    qty: 0,
    name: "Galaxy S9",
    description:
      "Puissant téléphone avec un écran Infinity de 5,8 pouces, un appareil photo de 12 MP à double ouverture.",
    brand: "Samsung",
    category: "android",
    gender: "4",
    weight: "128",
    quantity: 1,
    image: android3,
    rating: 4.7,
    price: 400,
    newPrice: 350,
    trending: true,
  },
  {
    _id: "fd25068a-9647-45ba-b44d-c8af1523148a",
    qty: 0,
    name: "Galaxy S10",
    description:
      "Téléphone avec écran Infinity de 6,1 pouces, triple appareil photo de 12 MP et lecteur d'empreintes digitales à ultrasons.",
    brand: "Samsung",
    category: "android",
    gender: "10",
    weight: "256",
    quantity: 1,
    image: android4,
    rating: 3.8,
    price: 600,
    newPrice: 550,
  },
  {
    _id: "95cd381c-32cf-46e5-8a75-05d30a421d6b",
    qty: 0,
    name: "Galaxy Note 8",
    description:
      "Téléphone stylé avec écran Infinity de 6,3 pouces, stylet S Pen et double appareil photo de 12 MP.",
    brand: "Samsung",
    category: "android",
    gender: "8",
    weight: "128",
    quantity: 1,
    image: android6,
    rating: 3.5,
    price: 400,
    newPrice: 350,
  },
  {
    _id: "6033723f-a8db-4ad8-bfda-d191778141aa",
    qty: 0,
    name: "iPhone X",
    description:
      "Design révolutionnaire avec un écran Super Retina de 5,8 pouces et une technologie de reconnaissance faciale.",
    brand: "Apple",
    category: "ios",
    gender: "3",
    weight: "128",
    quantity: 1,
    image: ios7,
    rating: 4.3,
    price: 350,
    newPrice: 299,
  },
  {
    _id: "ac072970-8dac-42fe-8c31-a8fa6fd4b64a",
    qty: 0,
    name: "iPhone XR",
    description:
      "iPhone abordable avec un écran Liquid Retina de 6,1 pouces et une seule caméra de 12 MP.",
    brand: "Apple",
    category: "ios",
    gender: "3",
    weight: "128",
    quantity: 1,
    image: ios8,
    rating: 4.8,
    price: 400,
    newPrice: 349,
  },
  {
    _id: "8ad38385-1211-4192-8108-db851b4e9434",
    qty: 0,
    name: "iPhone XS",
    description:
      "iPhone haut de gamme avec un écran Super Retina de 5,8 pouces et un double appareil photo de 12 MP.",
    brand: "Apple",
    category: "ios",
    gender: "4",
    weight: "128",
    quantity: 7,
    image: ios9,
    rating: 4.8,
    price: 325,
    newPrice: 299,
  },
  {
    _id: "9e3419eb-e5f6-4813-8bf4-6d72b6498235",
    qty: 0,
    name: "Galaxy Note 20",
    description:
      "Téléphone avec écran Dynamic AMOLED de 6,7 pouces, stylet S Pen et triple appareil photo de 12 MP.",
    brand: "Samsung",
    category: "android",
    gender: "10",
    weight: "256",
    quantity: 7,
    image: android9,
    rating: 4.8,
    price: 150,
    newPrice: 125,
  },
  {
    _id: "a84d980e-cf9e-4607-b74d-68f7a1c45771",
    qty: 0,
    name: "iPhone 6S",
    description:
      "Petit iPhone avec une caméra de 12 MP et un écran Retina de 4,7 pouces.",
    brand: "Apple",
    category: "ios",
    gender: "2",
    weight: "32",
    quantity: 1,
    image: ios1,
    rating: 4.5,
    price: 125,
    newPrice: 99,
  },
  {
    _id: "6c800171-bea6-4cb2-811d-7c419a59dcb8",
    qty: 0,
    name: "Galaxy Note 9",
    description:
      "Téléphone avec écran Infinity de 6,4 pouces, stylet S Pen amélioré et double appareil photo de 12 MP.",
    brand: "Samsung",
    category: "android",
    gender: "8",
    weight: "256",
    quantity: 6,
    image: android7,
    rating: 4.1,
    price: 450,
    newPrice: 399,
    trending: true,
  },
  {
    _id: "9ca598d9-7cb5-4fb0-8455-b43028f9cb96",
    qty: 0,
    name: "Galaxy Note 10",
    description:
      "Téléphone avec écran Dynamic AMOLED de 6,3 pouces, stylet S Pen et triple appareil photo de 12 MP.",
    brand: "Samsung",
    category: "android",
    gender: "10",
    weight: "512",
    quantity: 1,
    image: android8,
    rating: 4.3,
    price: 650,
    newPrice: 499,
    trending: true,
  },
  {
    _id: "51db0e19-b0e0-4d6e-bce0-739f1bd37ba7",
    qty: 0,
    name: "iPhone 6S Plus",
    description:
      "Version plus grande de l'iPhone 6S avec un écran Retina de 5,5 pouces.",
    brand: "Apple",
    category: "ios",
    gender: "2",
    weight: "32",
    quantity: 5,
    image: ios2,
    rating: 2.8,
    price: 175,
    newPrice: 149,
    trending: true,
  },
  {
    _id: "35332c85-f853-407a-80f8-840069381a0d",
    qty: 0,
    name: "iPhone 7",
    description:
      "Téléphone élégant avec une caméra améliorée de 12 MP et une résistance à l'eau.",
    brand: "Apple",
    category: "ios",
    gender: "2",
    weight: "64",
    quantity: 1,
    image: ios3,
    rating: 4.7,
    price: 175,
    newPrice: 149,
  },
  {
    _id: "440cec02-21e1-4447-bdd9-d51482b7ce4b",
    qty: 0,
    name: "iPhone 7 Plus",
    description:
      "Version plus grande de l'iPhone 7 avec un double appareil photo de 12 MP.",
    brand: "Apple",
    category: "ios",
    gender: "3",
    weight: "64",
    quantity: 1,
    image: ios4,
    rating: 3.8,
    price: 225,
    newPrice: 199,
  },
  {
    _id: "77f519a8-a40f-443d-8c9e-5314b24cf06d",
    qty: 0,
    name: "iPhone 8",
    description:
      "Puissant iPhone avec une caméra de 12 MP et la capacité de recharge sans fil.",
    brand: "Apple",
    category: "ios",
    gender: "2",
    weight: "128",
    quantity: 1,
    image: ios5,
    rating: 3.5,
    price: 250,
    newPrice: 199,
  },
  {
    _id: "11a2bfb4-2acf-40da-a12f-60dfcce8ed95",
    qty: 0,
    name: "iPhone 8 Plus",
    description:
      "Version plus grande de l'iPhone 8 avec un double appareil photo de 12 MP.",
    brand: "Apple",
    category: "ios",
    gender: "3",
    weight: "128",
    quantity: 6,
    image: ios6,
    rating: 4.1,
    price: 300,
    newPrice: 249,
  },
];
